/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JOptionPane;


/**
 *
 * @author Owner
 */
public class login1 extends javax.swing.JFrame {

    /**
     * Creates new form login1
     */
    public login1() {
        
        this.setExtendedState(login1.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        initComponents();
        setTitle("production by Uda Gagah");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        sandi = new javax.swing.JLabel();
        nama_pengguna = new javax.swing.JTextField();
        sandi_pengguna = new javax.swing.JTextField();
        masuk = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("nama pengguna");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(167, 33, 167));

        jPanel1.setBackground(new java.awt.Color(204, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nama.setText("nama pengguna");
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 131, -1));

        sandi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sandi.setText("sandi pengguna");
        jPanel1.add(sandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 137, -1));

        nama_pengguna.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(nama_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 142, 35));

        sandi_pengguna.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(sandi_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 142, 34));

        masuk.setBackground(new java.awt.Color(255, 255, 153));
        masuk.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        masuk.setText("masuk");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });
        jPanel1.add(masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 128, 56));

        keluar.setBackground(new java.awt.Color(255, 255, 153));
        keluar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keluar.setText("keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 123, 56));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 279, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Silahkan Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Anda Memasuki Halaman Login");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        kotak_pesan();        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        kotak_pesan_login();
        String dataku[]=new String [2];
        dataku[0]="kefin";
        dataku[1]="1103";
        //"kefin",sandi="1103";
        if(dataku[0].equals(nama_pengguna.getText())&&dataku[1].equals(sandi_pengguna.getText()))
        {
            beranda masa_depan=new beranda();//Membuat Instant dari kelas Beranda
            masa_depan.main(dataku);//Menyimpan data dari array dataku ke method main pada kelas beranda
            masa_depan.setVisible(true);//Menampilkan kelas beranda
            this.dispose();
    }//GEN-LAST:event_masukActionPerformed
        else{
          int dialogButton = JOptionPane.showConfirmDialog (null, "sandi atau nama pengguna salah?","PERINGATAN",JOptionPane.WARNING_MESSAGE);  
        }
    }
    
    
    
    
                                        
          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }
 public void kotak_pesan(){
        int dialogButton = JOptionPane.showConfirmDialog (null, "Apakah Anda Yakin Akan Keluar?","PERINGATAN",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);

        if(dialogButton == JOptionPane.YES_OPTION) {
        System.exit(0);}
    }
 public void kotak_pesan_login(){
        int dialogButton = JOptionPane.showConfirmDialog (null, "apakah anda yakin masuk?","PERINGATAN",JOptionPane.WARNING_MESSAGE);
  
       if(dialogButton == JOptionPane.NO_OPTION) {
        System.exit(0);}
 }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton masuk;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField nama_pengguna;
    private javax.swing.JLabel sandi;
    private javax.swing.JTextField sandi_pengguna;
    // End of variables declaration//GEN-END:variables
}
